<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TheRadioVault.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\*.png" />
    <EmbeddedResource Include="Assets\*.html" />
    <EmbeddedResource Include="Assets\*.js" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Contracts\WebApiRoutes.cs" />
    <Compile Remove="Models\WebModels.cs" />
    <ProjectReference Include="..\TheRadioVault.Protocol\TheRadioVault.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TheRadioVault.Web.Tests" />
  </ItemGroup>
</Project>
